### ISSUE TITLE
Ajouter [La Mêlée de l'Adour] dans les partenaires

### ISSUE THREAD

**Issue by aliceb64** [agilepaysbasquedev/site-web#12]
Logo : http://lameleeadour.com/wp-content/uploads/2016/02/la-melee-adour-economie-numerique.png
Site : http://lameleeadour.com/

**Comment by Squallygator** [comment]
On a un deal avec eux cette année ?

**Comment by aliceb64** [comment]
yes, Christophe m'a appelé + mail. Il vont faire la com sur leurs réseaux/newsletter. Ils touchent bcp de monde.

**Comment by aliceb64** [comment]
Super !
 
Notre page est prête : lameleeadour.com/agile-pays-basque-22-et-23-septembre-2017-a-bidart
Si tu as un autre visuel, merci de me le communiquer, je n’en ai pas trouvé sur le web pour cette 2ème édition.
 
Un emailing save the date part demain et un premier relai sur nos réseaux sociaux sera fait également demain 😊
 
Bonne continuation et à bientôt
 
Christophe
Cofondateur La Mêlée Adour
