### ISSUE TITLE
Ajouter une thématique [Infos Pratiques / Hébergement]

### ISSUE THREAD

**Issue by aliceb64** [agilepaysbasquedev/site-web#13]
Hébergement:
Chaque participant gère son hébergement. 

Vendredi : ESTIA
Nous avons négocié des tarifs préférentiels avec l'Hotel Fast Hotel qui se situe à 10 mn à pied du lieu de la conférence du VENDREDI : http://www.fasthotel-biarritz-bidart.com/
Relais Fasthôtel **
1350 Avenue de Bayonne
D 810
64210 BIDART
Tél : 05.59.23.01.09.
Fax : 05.59.23.15.92.
E-Mail : bidartbiarritz@fasthotel.com

C'est un hôtel 2 étoiles, le mobilier des chambres vient d’être changé et les salles de bains sont neuves.
Chambre pour 1 ou 2 personnes – 56 € au lieu de 62 €
Le petit déjeuner est de 7€ sous forme de buffet sucré/salé.
La taxe de séjour de 0.90€/personne.
Pour réserver : téléphonez au 05 59 23 01 09 ou par mail bidartbiarritz@fasthotel.com en donnant la référence agile pays basque pour bénéficier du tarif préférentiel. 
Les réservations peuvent être modifiées sans frais jusqu’au jour de votre arrivée.

Samedi : Centre de Thalasso ATLANTHAL :
http://www.atlanthal.com/content/7-hotel-les-terrasses-anglet …

Tarif préférentiel Hôtel LES TERRASSES d’ATLANTHAL 3*
Chambre et petit déjeuner single (1 personne) : 93 € par chambre et par nuit
Chambre et petit déjeuner double ou twin (2 personnes) : 132 € par chambre et par nuit
A ajouter la taxe de séjour : 1.35 € par personne et par nuit
Accès offert à l’espace aquatique LE LAGON et au FITNESS

Tarif préférentiel Hôtel ATLANTHAL 4*
Chambre et petit déjeuner single (1 personne) : 124 € par chambre et par nuit
Chambre et petit déjeuner double ou twin (2 personnes) : 184 € par chambre et par nuit
A ajouter la taxe de séjour : 1.80 € par personne et par nuit
Accès offert à l’espace aquatique LE LAGON et au FITNESS

**Comment by Squallygator** [comment]
On peut mais ne faut il pas privilégier le logement des orateurs ? d'abord

**Comment by aliceb64** [comment]
on envoie cette partie, j'en ai marre de faire des réponses individuelles à tous.

**Comment by Squallygator** [comment]
@aliceb64 on relance le sujet ?

**Comment by aliceb64** [comment]
je pense que oui (mais il faut être sûr des lieux).
