### ISSUE TITLE
Programme: Ne créez pas un produit inutile! Concentrez vous sur la valeur.

### ISSUE THREAD

**Issue by ghost** [agilepaysbasquedev/site-web#51]
Alice Barralon - 15h30 - Amphi

**Comment by aliceb64** [comment]
Public : Tout public

Blabla sur moi :
Artisan agiliste, et développeur sur mes temps libres. Je forme, dé- forme et transforme des personnes en les accompagnants dans les bonnes pratiques de développement et de management agile (formation et coaching). Co-fondatrice l’événement AgilePaysBasque.

Le contenu : 
"Il n’y a rien de plus inutile que de faire avec efficacité quelque chose qui ne doit pas du tout être fait." -Peter Drucker
Cette phrase vous parle ? Et bien venez ! 
Nous parlerons de la vie du produit, de son idée à sa mise sur le marché en se concentrant sur la VALEUR.
#LeanEntreprise #StoryMapping
