### ISSUE TITLE
Orateurs - Flag 2016 ne renvoit pas vers la bonne page

### ISSUE THREAD

**Issue by Squallygator** [agilepaysbasquedev/site-web#67]
Exemple : sur https://agilepaysbasquedev.github.io/site-web/speakers/ 
si on va sur Fabrice Aimetti et qu'on clique sur [2016] ça redirige vers https://agilepaysbasquedev.github.io/site-web/speakers/2016 qui n'existe pas.

Alors que sur https://agilepaysbasquedev.github.io/site-web/schedule/#session-11152
si on clique sur [2016] ça redirige bien vers le programme de l'édition 2016

3 options envisageable: 
- On enlève le lien du flag 2016
- Dans les 2 cas le 2016 renvoi vers  le programme de l'édition 2016
- On créé un page orateurs2016

**Comment by ghost** [comment]
Je supprimerais le flag, je ne vois pas trop l'utilité (voire presque c'est un peu confus). Pas besoin d'avoir une page orateurs 2016, le prog 2016 suffit à min avis.
