### ISSUE TITLE
Billetterie : Liens https vers la plateforme en dessous de l'iframe

### ISSUE THREAD

**Issue by Squallygator** [agilepaysbasquedev/site-web#8]
Remarque faite pas Chris Deniaud sur Twitter.
"C'est déconcertant de ne pas voir le https, quand on navigue sur la billetterie"
Je lui ai dit qu'on prenait le point.
J'ai eu le meme reflexe il y a quelques temps sur un autre site :
http://www.atabal-biarritz.fr/index.php/fr/prog/billetterie
Ils ont rajouté un bouton "Paiement sécurisé" avec un lien vers la billetterie externe.
On a qu'a faire pareil

**Comment by nicolasmingo** [comment]
Je suis d'accord. C'est une des raisons pour lesquelles je n'aime pas les iframes.

**Comment by nicolasmingo** [comment]
Autre solution : mettre le site en https.
https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

**Comment by Squallygator** [comment]
C'est encore mieux effectivement

**Comment by nicolasmingo** [comment]
je viens de suivre la procédure. le site est maintenant en https. (il faut attendre un jour pour que tous les DNS soient à jour)

**Comment by Squallygator** [comment]
On verra demain du coup
