### ISSUE TITLE
Repas : Samedi midi

### ISSUE THREAD

**Issue by aliceb64** [agilepaysbasquedev/site-web#86]
Restaurant les BAHINES
(Eau minérale, café et vin sur la base d’une bouteille pour 3 personnes)     

Entrée:
Crumble de légumes du moment (POUR LES VEGAN - prévoir environ 30% des repas)
Chiffonnade de Serrano et guindillas

Plat chaud:
Bar rôti au romarin et ses légumes à la plancha (prévoir 40% des plats)
Pièce de bœuf, beurre maître d’hôtel et ses frites maison  (prévoir 60% des plats)

Déssert:
Buffet de desserts  (pour tout le monde)

**Comment by Squallygator** [comment]
Trop tard
